
services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: >
      ganache-cli --host 0.0.0.0 --port 8545 
      --accounts 50
      --defaultBalanceEther 1000
      --deterministic
      --acctKeys /data/ganache-accounts.json
    volumes:
      - ./ganache-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
